ALTER TABLE coupons ADD COLUMN IF NOT EXISTS is_ocr_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS ocr_proof_url VARCHAR;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS escrow_status VARCHAR DEFAULT 'NONE';
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS buyer_id INTEGER;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS seller_id INTEGER;
