events {}

http {

    upstream frontend {
        server frontend:5173;
    }

    upstream backend {
        server backend:8000;
    }

    #
    # HTTP -> HTTPS Redirect
    #
    server {

        listen 80;

        server_name rewardshub.sreeram.site;

        return 301 https://$host$request_uri;

    }

    #
    # HTTPS Server
    #
    server {

        listen 443 ssl;

        server_name rewardshub.sreeram.site;

        ssl_certificate
            /etc/letsencrypt/live/rewardshub.sreeram.site/fullchain.pem;

        ssl_certificate_key
            /etc/letsencrypt/live/rewardshub.sreeram.site/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_prefer_server_ciphers on;

        #
        # Frontend
        #
        location / {

            proxy_pass http://frontend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

        #
        # Backend API
        #
        location /api/ {

            proxy_pass http://backend/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

        #
        # Swagger
        #
        location /docs {

            proxy_pass http://backend/docs;

        }

        location /openapi.json {

            proxy_pass http://backend/openapi.json;

        }

    }

}
